### ISSUE TITLE
Feature request: Victron EV charger

### ISSUE THREAD

**Issue by patatman** [tomer-w/ha-victron-mqtt#1]
Following along from the MQTT relay topic, this looks very promising! 
I do have a niche product from Victron, that is the EV charger. Below is the MQTT configuration I use to control the EVcharger, I know there are more topics, but those are less relevant I think.
If your goal is to integrate ALL options, I'll have to monitor the MQTT messages to see what's passing by. 

Maybe I'll have some time to contribute to a PR, but I don't have much experience with a Custom Integration. 

```yaml
select:
  - name: "Ev charger Mode"
    unique_id: victron_ev charger
    object_id: victron_ev charger
    options:
      - Auto
      - Manual
      - Scheduled charge
    state_topic: "victron/N/<system_id>/evcharger/40/Mode"
    value_template: >
      {% if value_json.value == 0 %}
        Manual
      {% elif value_json.value == 1 %}
        Auto
      {% elif value_json.value == 2 %}
        Scheduled charge
      {% endif %}
    command_topic: "victron/W/<system_id>/evcharger/40/Mode"
    command_template: >
      {% set value_map = {
            "Manual": 0,
            "Auto": 1,
            "Scheduled charge": 2,
          }
      %}
      { "value": {{ value_map[value] }}}
    device:
      {
        identifiers: ["Victron Cerbo GX"],
        manufacturer: "Victron Energy",
        model: "Cerbo GX",
        name: "Cerbo GX",
      }

switch:
  - name: "Ev charger charge"
    unique_id: victron_ev charger charge
    object_id: victron_ev charger charge
    command_topic: "victron/W/<system_id>/evcharger/40/StartStop"
    payload_on: '{"value": 1}'
    payload_off: '{"value": 0}'
    state_topic: "victron/N/<system_id>/evcharger/40/StartStop"
    value_template: "{{ value_json.value | int }}"
    state_on: "1"
    state_off: "0"
    device:
      {
        identifiers: ["Victron Cerbo GX"],
        manufacturer: "Victron Energy",
        model: "Cerbo GX",
        name: "Cerbo GX",
      }

binary_sensor:
  - name: "EV Charger Connected"
    unique_id: "victron_ev_charger_connected"
    object_id: "victron_ev_charger_connected"
    state_topic: "victron/N/<system_id>/evcharger/40/Connected"
    value_template: "{{ value_json.value }}"
    payload_off: "0"
    payload_on: "1"
    device_class: plug
    device:
      identifiers: ["Victron Cerbo GX"]
      manufacturer: "Victron Energy"
      model: "Cerbo GX"
      name: "Cerbo GX"

  - name: "Ev charger connected"
    unique_id: victron_ev charger connected
    object_id: victron_ev charger connected
    state_topic: "victron/N/<system_id>/evcharger/40/Connected"
    value_template: >
      {% if value_json.value == 0 %}
        No
      {% elif value_json.value == 1 %}
        Yes
      {% else %}
        Error - No Data
      {% endif %}
    device:
      {
        identifiers: ["Victron Cerbo GX"],
        manufacturer: "Victron Energy",
        model: "Cerbo GX",
        name: "Cerbo GX",
      }
sensor:
  - name: "Ev charger current"
    unique_id: victron_ev charger current
    object_id: victron_ev charger current
    state_class: measurement
    device_class: current
    unit_of_measurement: A
    icon: mdi:current-dc
    state_topic: "victron/N/<system_id>/evcharger/40/Current"
    value_template: "{{ value_json.value | round(2) }}"
    device:
      {
        identifiers: ["Victron Cerbo GX"],
        manufacturer: "Victron Energy",
        model: "Cerbo GX",
        name: "Cerbo GX",
      }

  - name: "EV Charger Power" 
    unique_id: "victron_evcharger_40_ac_l1_power"
    state_topic: "victron/N/<system_id>/evcharger/40/Ac/L1/Power"
    value_template: "{{ value_json.value | float(0) | round(0) }}"
    device_class: "power"
    unit_of_measurement: "W"
    icon: "mdi:flash"
    device:
      {
        identifiers: ["Victron Cerbo GX"],
        manufacturer: "Victron Energy",
        model: "Cerbo GX",
        name: "Cerbo GX",
      }


number:
  - name: "Ev charger set current"
    unique_id: victron_ev charger set current
    object_id: victron_ev charger set current
    device_class: current
    unit_of_measurement: A
    icon: mdi:current-dc
    min: 0
    max: 16
    step: 1
    mode: box
    state_topic: "victron/N/<system_id>/evcharger/40/SetCurrent"
    command_topic: "victron/W/<system_id>/evcharger/40/SetCurrent"
    command_template: '{"value": {{ value }} }'
    value_template: "{{ value_json.value | round(1) }}"
    device:
      {
        identifiers: ["Victron Cerbo GX"],
        manufacturer: "Victron Energy",
        model: "Cerbo GX",
        name: "Cerbo GX",
      }
```
